# Generated by Django 4.2.3 on 2023-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_alter_submission_submission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_file',
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_title',
            field=models.CharField(default='Submission Title', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='summary',
            field=models.TextField(blank=True, default='Summary', null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='background_image',
            field=models.ImageField(upload_to='hackathon_images/'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_image',
            field=models.ImageField(upload_to='hackathon_images/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.FileField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], upload_to='hackathon_submissions/'),
        ),
    ]
