# Generated by Django 4.2.3 on 2023-08-05 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathons', '0004_alter_hackathonregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hackathons.hackathonregistration'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
